version: "3.0"

services:
  web-service:
    build: .
    ports: 
      - 3000:3000
    depends_on: 
      - mongodb
    restart: always

  mongodb:
    image: mongo:4.0
    volumes: 
      - ./data/db:/data/db
    restart: always
